### ISSUE TITLE
Generate map roulette assets

### ISSUE THREAD

**Issue by steveoh** [agrc/collaborative-trailheads#4]
A map roulette challenge requires a GeoJSON file of locations and attributes. 

From the map roulette help

> A common option is to use a GeoJSON file you already have. This could be great if you have an approved source of external data you would like to manually add to OSM. Tools like [QGIS](https://gis.stackexchange.com/questions/91812/convert-shapefiles-to-geojson) and [gdal](http://www.gdal.org/drv_geojson.html) can convert things like Shapefiles to GeoJSON. When you convert, make sure that you use unprojected lon/lat on the WGS84 datum (EPSG:4326), because this is what MapRoulette uses internally.
> 
> Note: for challenges with a large number of tasks, we recommend using a [line-by-line](https://learn.maproulette.org/documentation/line-by-line-geojson/) format instead, which is much more efficient to process. Some advanced features are only available when the line-by-line format is used.

- [x] Generate a GeoJSON file with the locations we want reviewed in MapRoulette

**Comment by eneemann** [comment]
I created a GeoJSON file and uploaded it to the MapRoulette challenge that I started.  It ingested correctly and created tasks for all 725 locations.

**Comment by steveoh** [comment]
Can you paste the geojson in a gist and link it here please!

**Comment by eneemann** [comment]
Here's the geojson:
[https://gist.github.com/eneemann/c084806f3fa5dbde8c74f381db9cf698](https://gist.github.com/eneemann/c084806f3fa5dbde8c74f381db9cf698)
