### ISSUE TITLE
Privately test map roulette

### ISSUE THREAD

**Issue by steveoh** [agrc/collaborative-trailheads#5]
Privately publish the challenge to make sure it looks great

**Comment by eneemann** [comment]
Here's the intial version of the MapRoulette Challenge that I created: [https://maproulette.org/browse/challenges/28673](https://maproulette.org/browse/challenges/28673)

**Comment by gregbunce** [comment]
how often should we refresh the data (json) in the maproulette challenge?  is that process automatable?

**Comment by steveoh** [comment]
Why would it need to be refreshed?

**Comment by gregbunce** [comment]
after discussing it at our meeting today i realize it wouldn't.  that comment can be ignored.
