### ISSUE TITLE
Drive engagement

### ISSUE THREAD

**Issue by steveoh** [agrc/collaborative-trailheads#6]
- [x] #10
- [x] #9
- [x] #11

**Comment by gregbunce** [comment]
my goal is to have the engagement piece (blog post / instructional video) on our website by thanksgiving.

**Comment by gregbunce** [comment]
here's a [link](https://vimeo.com/776287631/3f1e8b7605) to the video that i'll include in the brief blog post about this project.

**Comment by gregbunce** [comment]
it's a little long so i'll make a note in the blog post and the video notes to jump to 5 mins in to get to the map challenge demo. 

also, pardon my mix-up of open sgid and open data (ahh!).

**Comment by gregbunce** [comment]
the video is a bit long and i missed the mark on few things, so i'm planning on redoing the video after i finish the blog post.   shooting for a shorter clip and also to make better use of the tags we've identified as desired.  

if you have any comments or suggestions for the next video i'd love to hear them.  steve sent me some valuable feedback already.

**Comment by steveoh** [comment]
I think we should do a 3 part series. The first one being like yay you can contribute to the SGID through open street map. We are so excited. Go sign up and here is the map roulette to make it happy. See how many points you can get and let us know the prizes we should give away when you win. yay! 🎉  Go for a hike and lets make open street map and the sgid better together!

The next should be how to use map roulette and one of the osm editers. Quick paced, use these buttons for the different scenarios, how to add tags, guidance on what to put etc, move/add features, yada yada, how to save the edits and how to let map roulette know you made them to get your points. And write a good message (if they need one). 

The last should be here are some tools and things I use and you might find helpful to complete the tasks if you want to help but don't have intimate knowledge or feel like driving for a hike to check it out first hand.

**Comment by nathankota** [comment]
The video is a great start, and could be truncated into a couple concise pieces to align with Steve's three-part-series idea, which is a good one.
